import type { LexisSettings } from "./types";
import { LEXIS_BRIDGE_DEFAULT_PORT } from "./constants";

export type DefaultLexisSettings = Omit<LexisSettings, "dicts" | "vocabFolders" | "excludeTags">;

export const DEFAULT_SETTINGS: DefaultLexisSettings = {
  language: "zh",
  vocabTags: "",
  includeAliases: true,
  aliasSources: "",
  inlineEntriesEnabled: true,
  inlineEntryDelimiter: "::",
  inlineClassificationMode: "heading",
  inlineCategoryColors: {},
  inlineCategoryOpacity: {},
  inlineCategoryHighlight: {},
  inlineFileColors: {},
  inlineFileOpacity: {},
  inlineFileHighlight: {},
  inlineSourceHighlight: {},
  inlineCollapsedGroups: {},
  inlineCategoryOrder: [],
  inlineFileOrder: [],
  inlineCategoryOrderByParent: {},
  enableHighlight: true,
  enableLivePreview: true,
  highlightStyle: "wavy",
  highlightColor: "",
  highlightOpacity: 1,
  popoverWidth: 460,
  popoverMaxHeight: 420,
  popoverFontSize: 14,
  hoverDelayMs: 250,
  fadeByMemory: true,
  fadeFloor: 0.25,
  hoverFeedback: true,
  hoverFeedbackDays: 3,
  retireCandidateDays: 90,
  tagRules: [],
  showRelated: true,
  showOccurrences: true,
  includePdfOccurrences: true,
  occurrenceLimit: 6,
  occurrenceFolders: "",
  requestRetention: 0.9,
  newPerDay: 20,
  maxReviewsPerSession: 200,
  reviewLog: {},
  reviewHistory: {},
  syntaxCardStates: {},
  suspendedReviewItems: {},
  showReviewMetadata: false,
  flashcardInlineTemplate: "{{question}}::{{answer}}",
  flashcardBidirectionalTemplate: "{{sideA}}:::{{sideB}}",
  flashcardBlockTemplate: "{{question}}??\n{{answer}}",
  flashcardClozeTemplate: "=={{answer}}==",
  newWordTemplate: "template/单词模板.md",
  emptyNotePreset: "blank",
  occurrenceTemplate: "#### 出处\n> {{sentence}}{{sourceSuffix}}",
  annotationHeading: "",
  annotationImageLocation: "obsidian",
  annotationImageFolder: "",
  cardFront: "note",
  reviewBottomSpace: 70,
  lastReviewLinkSource: "",
  lastReviewHub: "",
  bridgeEnabled: false,
  bridgePort: LEXIS_BRIDGE_DEFAULT_PORT,
  bridgeToken: "",
  selectionPill: true,
  lastSelectionFolder: "",
  enablePdfHighlight: true,
};
