"use strict";

import * as obsidian from "obsidian";
import { Component, Plugin, TFile } from "obsidian";
import type { Occurrence, OccurrenceSearch } from "./occurrence-search";
import type { InlineCategoryOccurrence, LexisEntry, LexisSettings, LexisStats, ReviewCardState, ReviewHistoryEvent, ReviewItem, ReviewOptions, ReviewStateSnapshot } from "./types";
import type { EncounterMutation, EncounterSummary, EncounterStore } from "./encounter-store";
import type { ReviewSchedule } from "./review-scheduler";
import type { WorkspaceDocuments } from "./workspace-documents";
import type { createI18n } from "./i18n";
import type { createTemplateProvider } from "./template-provider";
import type { ExcalidrawHighlights } from "./excalidraw-highlights";

export type TranslationVars = Record<string, string | number | boolean | null | undefined>;
export type ReviewCard = ReviewCardState & { history?: ReviewHistoryEvent[] };
export type Schedule = ReviewSchedule;
export type Lifecycle = { archived: boolean; retired: boolean; pinned: boolean };
export type Relation = { path: string; basename: string };
export type RelationBag = Record<string, Relation[]>;
export type BridgeRuntime = { running: boolean; generateToken(): string; start(): void; stop(): void; restart(): void };
export type AddSelectionOptions = { openExisting?: boolean; alias?: string; sentence?: string; sourceFile?: TFile | null; page?: number };
export type HighlightPage = { leaf: obsidian.WorkspaceLeaf; container: HTMLElement; key: string };
export type HomeOpenLocation = "center" | "sidebar";

export const errorMessage = (error: unknown): string => error instanceof Error ? error.message : typeof error === "string" ? error : "Unknown error";

export class LexisPluginBase extends Plugin {
  declare settings: LexisSettings;
  declare index: Map<string, LexisEntry>;
  declare stats: LexisStats;
  declare inlineCategoryOccurrences: InlineCategoryOccurrence[];
  declare inlineCategories: { name: string; count: number }[];
  declare vocabPaths: Set<string>;
  declare inlineSourcePaths: Set<string>;
  declare i18n: ReturnType<typeof createI18n>;
  declare templateProvider: ReturnType<typeof createTemplateProvider>;
  declare occurrenceSearch: OccurrenceSearch;
  declare bridge: BridgeRuntime | null;
  declare liveAvailable: boolean;
  declare statusBarEl: HTMLElement | null;
  declare _pattern: string | null;
  declare _indexBuildId: number;
  declare _indexKeysByCompact: Map<string, string>;
  declare _matchKeysByCompact: Map<string, string>;
  declare _rebuildTimer: number | null;
  declare _popover: HTMLElement | null;
  declare _popoverComp: Component | null;
  declare _hideTimer: number | null;
  declare _showTimer: number | null;
  declare _showTarget: HTMLElement | null;
  declare _occCache: Map<string, Occurrence[]>;
  declare _encounters: Record<string, EncounterSummary>;
  declare _encounterStore: EncounterStore;
  declare _encPending: EncounterMutation[];
  declare _encWriting: Promise<void> | null;
  declare _encRevision: number;
  declare _encRelocating: boolean;
  declare _encSaveTimer: number;
  declare _encounterDedup: Record<string, number>;
  declare _pageHighlightState: WeakMap<obsidian.WorkspaceLeaf, { key: string; hidden: boolean }>;
  declare _reviewSessions: WeakMap<object, unknown>;
  declare _workspaceDocuments: WorkspaceDocuments;
  declare _excalidrawHighlights: ExcalidrawHighlights;
  declare _selPill: HTMLElement | null;
  declare _mobileTapStart: { pointerId: number; x: number; y: number; time: number; target: HTMLElement } | null;
  declare _mobileTapClick: { x: number; y: number; time: number } | null;
  declare highlightElement: (el: HTMLElement, ctx: obsidian.MarkdownPostProcessorContext) => void;
  declare renderLexisBlock: (el: HTMLElement, ctx: obsidian.MarkdownPostProcessorContext, src: string) => Promise<void>;
  declare renderHeatmap: (el: HTMLElement) => void;
  declare renderHomeBlock: (el: HTMLElement) => void;
  declare setupLiveExtension: () => void;
  declare setupPdfHighlight: (document?: Document) => void;
  declare setupEpubIframeHighlight: (document?: Document) => void;
  declare teardownPdfHighlight: () => void;
  declare teardownEpubIframeHighlight: () => void;
  declare onMouseOver: (event: MouseEvent) => void;
  declare onMouseMove: (event: MouseEvent) => void;
  declare onMouseOut: (event: MouseEvent) => void;
  declare onClick: (event: MouseEvent) => void;
  declare onPointerDown: (event: PointerEvent) => void;
  declare onPointerMove: (event: PointerEvent) => void;
  declare onPointerUp: (event: PointerEvent) => void;
  declare onPointerCancel: () => void;
  declare maybeShowSelPill: (event: MouseEvent) => void;
  declare removePopover: () => void;
  declare removeSelPill: () => void;
  declare currentHighlightPage: () => HighlightPage | null;
  declare toggleCurrentPageHighlights: (page: HighlightPage) => void;
  declare syncActivePageHighlightState: (leaf?: obsidian.WorkspaceLeaf | null) => void;
  declare maybeRebuild: (file: TFile | null, oldPath?: string) => void;
  declare scheduleRebuild: () => void;
  declare isInlineSourceFile: (file: TFile | null | undefined) => boolean;
  declare rebuildIndex: (notify: boolean) => Promise<LexisStats>;
  declare resolveIndexKey: (value: string) => string;
  declare resolveMatchKey: (value: string) => string;
  declare inlineStyleForEntry: (entry: LexisEntry | undefined, options?: { external?: boolean; pdf?: boolean }) => string;
  declare renderNoteInto: (el: HTMLElement, file: TFile, component: Component) => Promise<void>;
  declare insertOccurrence: (data: string, vars: Record<string, unknown>) => string;
  declare normalizeFolder: (folder: string) => string;
  declare inVocabFolder: (path: string) => boolean;
  declare getTags: (file: TFile) => Set<string>;
  declare dictColorForFile: (file: TFile | null | undefined) => string | null;
  declare inlineCategoryColor: (entry: LexisEntry) => string;
  declare occurrenceHeadingText: () => string;
  declare occurrenceSentenceFromSection: (section: string) => string;
  declare renderTemplate: (template: string, vars: Record<string, unknown>) => string;
  declare inlineDelimiter: () => string;
  declare openInlineEntry: (entry: LexisEntry, newTab: boolean) => Promise<void>;
  declare applyPopoverAppearance: (popover: HTMLElement) => void;
  declare updateStatusBar: () => void;
  declare bridgeWordList: () => unknown;
  declare bridgeWordDetail: (key: string | null) => Promise<unknown>;
  declare bridgeWordOccurrences: (key: string | null) => Promise<unknown>;
  declare bridgeDeleteWord: (key: string) => Promise<unknown>;
  declare bridgeAddWord: (payload: Record<string, unknown>) => Promise<unknown>;
  declare bridgeTagWord: (payload: Record<string, unknown>) => Promise<unknown>;
  declare bridgeAnnotate: (payload: Record<string, unknown>) => Promise<unknown>;
  declare bridgeMoveWord: (payload: Record<string, unknown>) => Promise<unknown>;
  declare bridgeEncounter: (payload: Record<string, unknown>) => Promise<unknown>;
  declare addAliasToFile: (file: TFile, alias: string) => Promise<void>;
  declare attachAlias: (aliasText: string, file: TFile) => Promise<void>;
  declare readSyntaxCardState: (id: string) => ReviewCardState;
  declare snapshotReviewItem: (item: ReviewItem) => ReviewStateSnapshot;
  declare applyReviewItemSchedule: (item: ReviewItem, schedule: Schedule) => Promise<void>;
  declare suspendReviewItem: (item: ReviewItem) => Promise<void>;
  declare restoreReviewItem: (item: ReviewItem, snapshot: ReviewStateSnapshot) => Promise<void>;
  declare logReviewItem: (item: ReviewItem, schedule: Schedule, grade: number, retentionBefore: number) => Promise<string>;
  declare undoReviewItemLog: (item: ReviewItem, eventId: string) => Promise<void>;
  declare collectReviewFolders: () => string[];
  declare collectReviewTags: () => string[];
  declare collectSuspendedReviewItems: () => Promise<import("./types").SuspendedReviewEntry[]>;
  declare buildQueue: (options?: ReviewOptions) => Promise<ReviewItem[]>;
  declare migrateSyntaxCardPath: (file: TFile, oldPath: string) => Promise<void>;
}
